# Generated by Django 5.2.1 on 2026-05-24 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('lectura_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DANADO', 'Dañado'), ('SUSPENDIDO', 'Suspendido'), ('RETIRADO', 'Retirado')], default='ACTIVO', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('abonado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medidores', to='abonados.abonado')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medidor',
                'verbose_name_plural': 'Medidores',
                'ordering': ['numero'],
            },
        ),
    ]
