# Generated by Django 5.2.1 on 2026-06-06 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonados', '0002_abonado_estado_servicio'),
        ('medidores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioMedidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_cambio', models.DateField()),
                ('lectura_final_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lectura_inicial_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.TextField()),
                ('abonado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abonados.abonado')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('medidor_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_como_anterior', to='medidores.medidor')),
                ('medidor_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_como_nuevo', to='medidores.medidor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
