# Generated by Django 5.2.1 on 2026-05-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonado',
            name='estado_servicio',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20),
        ),
    ]
