# Generated by Django 5.2.1 on 2026-05-25 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('PAGO', 'Pago'), ('ANULAR_PAGO', 'Anular pago'), ('ANULAR_FACTURA', 'Anular factura'), ('GENERAR_FACTURA', 'Generar factura'), ('LECTURA', 'Lectura'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión')], max_length=50)),
                ('modulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('objeto_id', models.CharField(blank=True, max_length=100)),
                ('objeto_repr', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditoría',
                'ordering': ['-creado_en'],
            },
        ),
    ]
