# Generated by Django 5.2.1 on 2026-06-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_alter_auditoria_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('PAGO', 'Pago'), ('ANULAR_PAGO', 'Anular pago'), ('ANULAR_FACTURA', 'Anular factura'), ('GENERAR_FACTURA', 'Generar factura'), ('LECTURA', 'Lectura'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('IMPORTAR_LECTURAS', 'Importar lecturas'), ('SUSPENDER_SERVICIO', 'Suspender servicio'), ('RECONECTAR_SERVICIO', 'Reconectar servicio'), ('CREAR_MULTA', 'Crear multa'), ('COBRAR_MULTA', 'Cobrar multa'), ('ANULAR_MULTA', 'Anular multa'), ('AGREGAR_RUBRO', 'Agregar rubro'), ('CREAR_MEDIDOR', 'Crear medidor'), ('EDITAR_MEDIDOR', 'Editar medidor'), ('CAMBIAR_MEDIDOR', 'Cambiar medidor'), ('EXPORTAR_REPORTE', 'Exportar reporte')], max_length=50),
        ),
    ]
