"""
Django settings for configuracion project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env(
    DEBUG=(bool, False),
    SESSION_COOKIE_AGE=(int, 3600),
    SESSION_COOKIE_NAME=(str, "sistema_agua_sessionid"),
    CSRF_COOKIE_NAME=(str, "sistema_agua_csrftoken"),
    SECURE_SSL_REDIRECT=(bool, False),
    SECURE_HSTS_SECONDS=(int, 0),
    SECURE_HSTS_INCLUDE_SUBDOMAINS=(bool, False),
    SECURE_HSTS_PRELOAD=(bool, False),
    SESSION_COOKIE_SECURE=(bool, False),
    CSRF_COOKIE_SECURE=(bool, False),
    USE_X_FORWARDED_HOST=(bool, False),
    SECURE_PROXY_SSL_HEADER_ENABLED=(bool, False),
    ENABLE_DJANGO_EXTENSIONS=(bool, False),
    AXES_FAILURE_LIMIT=(int, 3),
    AXES_COOLOFF_TIME=(float, 0.25),
    TIME_ZONE=(str, "America/Guayaquil"),
    MASTER_DB_NAME=(str, ""),
    TENANT_DEFAULT=(str, "carabuela"),
    TENANT_DB_PREFIX=(str, "sistema_agua_"),
    TENANT_ADMIN_DB_NAME=(str, "postgres"),
    TENANT_ROUTE_MODE=(str, "path"),
)
environ.Env.read_env(os.path.join(BASE_DIR.parent, '.env'))


def lista_entorno(nombre, default=None):
    return [
        valor.strip()
        for valor in env.list(nombre, default=default or [])
        if valor.strip()
    ]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = env("SECRET_KEY")

DEBUG = env("DEBUG")

ALLOWED_HOSTS = lista_entorno(
    "ALLOWED_HOSTS",
    default=["localhost", "127.0.0.1"],
)

CSRF_TRUSTED_ORIGINS = lista_entorno("CSRF_TRUSTED_ORIGINS")

MASTER_DB_NAME = env("MASTER_DB_NAME") or env("DB_NAME")
TENANT_DEFAULT = env("TENANT_DEFAULT")
TENANT_SLUGS = lista_entorno(
    "TENANT_SLUGS",
    default=["carabuela", "esperanza", "pesillo"],
)
TENANT_DB_PREFIX = env("TENANT_DB_PREFIX")
TENANT_ADMIN_DB_NAME = env("TENANT_ADMIN_DB_NAME")
TENANT_ROUTE_MODE = env("TENANT_ROUTE_MODE")

SESSION_COOKIE_AGE = env("SESSION_COOKIE_AGE")
SESSION_COOKIE_NAME = env("SESSION_COOKIE_NAME")
CSRF_COOKIE_NAME = env("CSRF_COOKIE_NAME")
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True

SECURE_SSL_REDIRECT = env("SECURE_SSL_REDIRECT")
SECURE_HSTS_SECONDS = env("SECURE_HSTS_SECONDS")
SECURE_HSTS_INCLUDE_SUBDOMAINS = env("SECURE_HSTS_INCLUDE_SUBDOMAINS")
SECURE_HSTS_PRELOAD = env("SECURE_HSTS_PRELOAD")
SESSION_COOKIE_SECURE = env("SESSION_COOKIE_SECURE")
CSRF_COOKIE_SECURE = env("CSRF_COOKIE_SECURE")
USE_X_FORWARDED_HOST = env("USE_X_FORWARDED_HOST")

if env("SECURE_PROXY_SSL_HEADER_ENABLED"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'nucleo',
    'tenants',
    'usuarios',
    'panel',
    'abonados',
    'medidores',
    'tarifas',
    'lecturas',
    'facturacion',
    'pagos',
    'reportes',
    'auditoria',
    'configuracion_institucional',
    'multas',
    'servicios',
    "axes",
]

if env("ENABLE_DJANGO_EXTENSIONS"):
    INSTALLED_APPS.append("django_extensions")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'tenants.middleware.TenantPathMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "axes.middleware.AxesMiddleware",
]

ROOT_URLCONF = 'configuracion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'usuarios.context_processors.roles_usuario',
                'nucleo.context_processors.menu_sidebar',
            ],
            'builtins': [
                'tenants.templatetags.tenant_urls',
            ],
        },
    },
]

WSGI_APPLICATION = 'configuracion.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    },
    'master': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': MASTER_DB_NAME,
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
        'TEST': {
            'NAME': f'test_master_{MASTER_DB_NAME}',
            'DEPENDENCIES': [],
        },
    }
}

DATABASE_ROUTERS = [
    "tenants.db_router.TenantMasterRouter",
    "tenants.db_router.TenantOperationalRouter",
]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = env("TIME_ZONE")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'usuarios.Usuario'

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/panel/"
LOGOUT_REDIRECT_URL = "/login/"


# ==================================================
# DJANGO AXES - PROTECCIÓN CONTRA FUERZA BRUTA
# ==================================================

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Máximo de intentos fallidos
AXES_FAILURE_LIMIT = env("AXES_FAILURE_LIMIT")

# Bloqueo durante 15 minutos
AXES_COOLOFF_TIME = env("AXES_COOLOFF_TIME")

# Bloqueo por usuario + IP
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]

# Si inicia sesión correctamente, reinicia el contador
AXES_RESET_ON_SUCCESS = True

# Mostrar nuestra plantilla de login
AXES_LOCKOUT_TEMPLATE = "usuarios/login.html"

# Función personalizada para el mensaje
AXES_LOCKOUT_CALLABLE = "usuarios.views.axes_lockout_response"
