# Generated by Django 5.2.1 on 2026-05-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_pago_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='motivo_anulacion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
