# Generated by Django 5.2.1 on 2026-06-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_institucional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='cargo_representante',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='cargo_responsable_caja',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='pie_pagina',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='representante',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='configuracioninstitucional',
            name='responsable_caja',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
