# Generated by Django 5.2.1 on 2026-05-29 00:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspensionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_suspension', models.DateField(default=django.utils.timezone.localdate)),
                ('motivo_suspension', models.TextField()),
                ('estado', models.CharField(choices=[('SUSPENDIDO', 'Suspendido'), ('RECONECTADO', 'Reconectado'), ('ANULADO', 'Anulado')], default='SUSPENDIDO', max_length=20)),
                ('fecha_reconexion', models.DateField(blank=True, null=True)),
                ('observacion_reconexion', models.TextField(blank=True, default='')),
                ('motivo_anulacion', models.TextField(blank=True, default='')),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('abonado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suspensiones', to='abonados.abonado')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suspensión de servicio',
                'verbose_name_plural': 'Suspensiones de servicio',
                'ordering': ['-fecha_suspension'],
            },
        ),
    ]
