# Generated by Django 5.2.1 on 2026-05-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='lectura_registrada',
            field=models.BooleanField(default=False),
        ),
    ]
