# Generated by Django 5.2.1 on 2026-05-24 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ALCANTARILLADO', 'Alcantarillado'), ('MULTA', 'Multa'), ('OTRO', 'Otro')], max_length=30)),
                ('forma_calculo', models.CharField(choices=[('FIJO', 'Valor fijo'), ('PORCENTAJE', 'Porcentaje')], default='FIJO', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aplica_automaticamente', models.BooleanField(default=False)),
                ('vigente', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TarifaAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumo_base', models.DecimalField(decimal_places=2, help_text='Consumo incluido dentro del valor base.', max_digits=10)),
                ('valor_excedente', models.DecimalField(decimal_places=2, help_text='Valor a cobrar por cada unidad adicional de consumo.', max_digits=10)),
                ('vigente', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarifa de agua',
                'verbose_name_plural': 'Tarifas de agua',
                'ordering': ['nombre'],
            },
        ),
    ]
