# Generated by Django 5.2.1 on 2026-05-25 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RangoTarifaAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('desde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hasta', models.DecimalField(blank=True, decimal_places=2, help_text='Dejar vacío si no tiene límite superior.', max_digits=10, null=True)),
                ('valor_por_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangos', to='tarifas.tarifaagua')),
            ],
            options={
                'verbose_name': 'Rango de tarifa de agua',
                'verbose_name_plural': 'Rangos de tarifa de agua',
                'ordering': ['desde'],
            },
        ),
    ]
