# Generated by Django 5.2.1 on 2026-05-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_factura_saldo_pendiente_factura_total_pagado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='motivo_anulacion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
